/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as BibliothequeRouteImport } from './app/bibliotheque'
import { Route as IndexRouteImport } from './app/index'
import { Route as ParentsIndexRouteImport } from './app/parents/index'
import { Route as AventureIndexRouteImport } from './app/aventure/index'
import { Route as ParentsLieuxRouteImport } from './app/parents/lieux'
import { Route as ParentsImageModelRouteImport } from './app/parents/image-model'
import { Route as ParentsHeroesRouteImport } from './app/parents/heroes'
import { Route as ParentsElementsRouteImport } from './app/parents/elements'
import { Route as ParentsDoudousRouteImport } from './app/parents/doudous'
import { Route as AventureIdRouteImport } from './app/aventure/$id'

const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AventureIndexRoute = AventureIndexRouteImport.update({
  id: '/aventure/',
  path: '/aventure/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsLieuxRoute = ParentsLieuxRouteImport.update({
  id: '/parents/lieux',
  path: '/parents/lieux',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsImageModelRoute = ParentsImageModelRouteImport.update({
  id: '/parents/image-model',
  path: '/parents/image-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsHeroesRoute = ParentsHeroesRouteImport.update({
  id: '/parents/heroes',
  path: '/parents/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsElementsRoute = ParentsElementsRouteImport.update({
  id: '/parents/elements',
  path: '/parents/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsDoudousRoute = ParentsDoudousRouteImport.update({
  id: '/parents/doudous',
  path: '/parents/doudous',
  getParentRoute: () => rootRouteImport,
} as any)
const AventureIdRoute = AventureIdRouteImport.update({
  id: '/aventure/$id',
  path: '/aventure/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/aventure/$id': typeof AventureIdRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/aventure/': typeof AventureIndexRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/aventure/$id': typeof AventureIdRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/aventure': typeof AventureIndexRoute
  '/parents': typeof ParentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/aventure/$id': typeof AventureIdRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/aventure/': typeof AventureIndexRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bibliotheque'
    | '/aventure/$id'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/aventure/'
    | '/parents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bibliotheque'
    | '/aventure/$id'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/aventure'
    | '/parents'
  id:
    | '__root__'
    | '/'
    | '/bibliotheque'
    | '/aventure/$id'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/aventure/'
    | '/parents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliothequeRoute: typeof BibliothequeRoute
  AventureIdRoute: typeof AventureIdRoute
  ParentsDoudousRoute: typeof ParentsDoudousRoute
  ParentsElementsRoute: typeof ParentsElementsRoute
  ParentsHeroesRoute: typeof ParentsHeroesRoute
  ParentsImageModelRoute: typeof ParentsImageModelRoute
  ParentsLieuxRoute: typeof ParentsLieuxRoute
  AventureIndexRoute: typeof AventureIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventure/': {
      id: '/aventure/'
      path: '/aventure'
      fullPath: '/aventure/'
      preLoaderRoute: typeof AventureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/lieux': {
      id: '/parents/lieux'
      path: '/parents/lieux'
      fullPath: '/parents/lieux'
      preLoaderRoute: typeof ParentsLieuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/image-model': {
      id: '/parents/image-model'
      path: '/parents/image-model'
      fullPath: '/parents/image-model'
      preLoaderRoute: typeof ParentsImageModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/heroes': {
      id: '/parents/heroes'
      path: '/parents/heroes'
      fullPath: '/parents/heroes'
      preLoaderRoute: typeof ParentsHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/elements': {
      id: '/parents/elements'
      path: '/parents/elements'
      fullPath: '/parents/elements'
      preLoaderRoute: typeof ParentsElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/doudous': {
      id: '/parents/doudous'
      path: '/parents/doudous'
      fullPath: '/parents/doudous'
      preLoaderRoute: typeof ParentsDoudousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventure/$id': {
      id: '/aventure/$id'
      path: '/aventure/$id'
      fullPath: '/aventure/$id'
      preLoaderRoute: typeof AventureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliothequeRoute: BibliothequeRoute,
  AventureIdRoute: AventureIdRoute,
  ParentsDoudousRoute: ParentsDoudousRoute,
  ParentsElementsRoute: ParentsElementsRoute,
  ParentsHeroesRoute: ParentsHeroesRoute,
  ParentsImageModelRoute: ParentsImageModelRoute,
  ParentsLieuxRoute: ParentsLieuxRoute,
  AventureIndexRoute: AventureIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
